apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cf7he8mdl-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cf7he8mdl-dotnet-basic-gitops